### ISSUE TITLE
Sealed trait reader throws MatchError instead of Invalid

### ISSUE THREAD

**Issue by mechkg** [lihaoyi/upickle-pprint#101]
Trying to read wrong JSON as a tagged union type, e.g.:

    sealed trait T 

    object T {
      case class A(a: String) extends T
      case class B(b: Int) extends T
    }
    ...
    val x = read[T]("""{ "test" : "hello" }""")

results in a scala.MatchError (compiled with Scala.js):

    caught scala.MatchError: Obj(ArrayBuffer((test,Str(hello)))) (of class upickle.Js$Obj)
    $c_s_PartialFunction$$anon$1.apply__O__sr_Nothing$ @ PartialFunction.scala:253
    $c_s_PartialFunction$$anon$1.apply__O__O @ PartialFunction.scala:251
    $c_Lupickle_AttributeTagged$$anonfun$annotate$2.applyOrElse__Lupickle_Js$Value__F1__O @ Api.scala:49

Which points to [this code](https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/shared/src/main/scala/upickle/Api.scala#L49-L53) where there is an obviously unsafe match block.

Is this the expected behaviour?

**Comment by lihaoyi** [comment]
It is, kinda. we introduced it a while ago and I don't remember why lol. I think @tindzk needed it for something
