### ISSUE TITLE
Invalid code using upickle hangs compiler

### ISSUE THREAD

**Issue by ForNeVeR** [lihaoyi/upickle-pprint#107]
The following invalid code causes the compilation process to hang forever.

```scala
package ru.org.codingteam.icfpc

import upickle.default._

object Serializer {

  def deserialize[T : Reader](x: String): T = {
    read[T](x)
  }
}

object MapPrinter {

  def test() : Unit = {
    val d = Serializer.deserialize("")
  }
}
```

Reproduced with Scala 2.11.7,

```scala
libraryDependencies ++= Seq(
  "com.lihaoyi" %% "upickle" % "0.3.4"
)
```

Reproducible example can be found at https://github.com/codingteam/icfpc-2015/tree/scalac-bug (exactly that branch).

It is a problem of upickle macro implementation, or should I file that to scalac bugtracker?

**Comment by jrudolph** [comment]
I found a similar thing where I completely forgot the type argument to `read` which also hangs the compiler.
