### ISSUE TITLE
Derive.TypeKey lacks hashCode implementation

### ISSUE THREAD

**Issue by ghik** [lihaoyi/upickle-pprint#124]
`Derive.TypeKey` has `equals` overridden but does not properly override `hashCode`. This can lead to patologies like:

```scala
val tk1 = TypeKey(typeOf[String])
val tk2 = TypeKey(typeOf[java.lang.String])
tk1 == tk2 // true
tk1.hashCode == tk2.hashCode // false!!!
```

**Comment by Voltir** [comment]
I looked at this a bit and realized that I'm not actually sure what a proper hashcode would be.

**Comment by lihaoyi** [comment]
This has happened, more or less

**Comment by ghik** [comment]
I also saw shapeless implement `Type`-keyed maps. There was no `hashCode` implemented at all, but the consequences were avoided by using `ListMap` instead of `HashMap` :)
