### ISSUE TITLE
Add ability to print out passed in variable name aka a debug macro

### ISSUE THREAD

**Issue by pathikrit** [lihaoyi/upickle-pprint#131]
e.g.

```scala
val x = 23
val y  = "hello"
pprint.debug(x, y, x+y)
```

Should print:

```
x = 23, y = "hello", x.+y = "23hello"
```

See: https://github.com/adamw/scala-macro-debug

**Comment by lihaoyi** [comment]
that would be nice

**Comment by lihaoyi** [comment]
[Sourcecode 0.1.1](https://github.com/lihaoyi/sourcecode) lets you do this trivially, if someone wants to contribute this

**Comment by lihaoyi** [comment]
This has happened https://github.com/lihaoyi/upickle-pprint/blob/master/pprint/shared/src/main/scala/pprint/package.scala#L9
