### ISSUE TITLE
Derivation for seqish types should short-circuit before recursing on `W[T]`

### ISSUE THREAD

**Issue by stewSquared** [lihaoyi/upickle-pprint#137]
`SeqishW` in Implicits.scala with signature

 ```scala
implicit def SeqishW[T: W, V[_] <: Iterable[_]]: W[V[T]] = W[V[T]]
```

 can cause a needlessly long increase in compilation time. It first triggers a search for `W[T]`, even if it might not apply.

A fix was published by @patrick-premont and can be seen in [his fork of upickle](https://github.com/patrick-premont/upickle-pprint/commit/529b9fa6956b36d32fe56168209b5567a3127f1a). We use a similar fix to save ~600s compilation time in our code base. There are other workarounds (you can generate your own Writers or extend `AttributeTagged` with some of your own implicits to avoid forking), but it'd be nice to be able to use the standard  automatic typeclass derivation packed with upickle.

##### Background:

We're using slick with a large database and generate case classes for each row. We cross-compile these js and jvm and then use upickle to serialize these case classes.

We also have a typed ID, like so: `case class ID[SomeDataBaseRow](id: Int)`. The serialization of an `Id` is simple and doesn't need to recurse on `SomeDataBaseRow`, because you only need a `Writer[Int]`. When upickle tries to recurse, it essentially ends up deriving Writers for every table type in the database.

**Comment by lihaoyi** [comment]
Fixed by #138
