### ISSUE TITLE
Implicit PPrinters not identified

### ISSUE THREAD

**Issue by samuela** [lihaoyi/upickle-pprint#153]
My `build.sbt` looks something like

```scala
scalaVersion := "2.11.8"
libraryDependencies += "com.lihaoyi" %% "pprint" % "0.4.0"
```

And then

```scala
scala> import pprint._
import pprint._

scala> PPrint(new Object())
<console>:15: error: type mismatch;
 found   : Object
 required: pprint.PPrinter[?]
       PPrint(new Object())
              ^
```

Am I missing something?

**Comment by lihaoyi** [comment]
Yeah you should be using

```scala
scala> pprint.pprintln(new Object)
java.lang.Object@1ec8ad64
```

`PPrint` it usually used as a typeclass to allow pretty-printing, e.g. 

```scala
def log[T: PPrint](t: T) = {
  ...
  pprintln(t)
  ...
} 
```

The apply method on its companion is handy for constructing it, but generally shouldn't be used unless you're doing something special

**Comment by samuela** [comment]
Ah, ok. I was a bit confused because the website features an example that seems to use PPrint as a function:

```
scala> PPrint(new Object())
res35: String = java.lang.Object@54f880c0
```

How should I go about pretty printing something to a String instead of stdout?

**Comment by lihaoyi** [comment]
For that you can use `pprint.tokenize`.

If the docs are outdated I should go fix it...
