### ISSUE TITLE
upickle.Invalid$Data: String (data: 1)upickle.Invalid$Data: String (data: 1)

### ISSUE THREAD

**Issue by Sergey80** [lihaoyi/upickle-pprint#154]
```
import upickle.default._
import scala.scalajs.concurrent.JSExecutionContext.Implicits.queue

@JSExport
def posts() : Future[Seq[Post]] = {
  val txt = """[{
    "userId": 1,
    "id": 1,
    "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
  }]"""

  val p = read[Seq[Post]](txt)

  println(p)

  p

}

pp onFailure {
  case x => println(x)
}
```

println(x) prints: upickle.Invalid$Data: String (data: 1)

How to make it work?

Updated, the definition of post is: case class Post(userId: Long, id: Long, title: String, body: String)

**Comment by lihaoyi** [comment]
What's the definition of `Post`?

**Comment by Sergey80** [comment]
case class Post(userId: Long, id: Long, title: String, body: String)

**Comment by lihaoyi** [comment]
uPickle serializes `Long`s as `"1"` in order to avoid corruption/truncation for large numbers in Scala.js. If they're coming down as JSON Numbers, you need to type them as `Int`s or `Double`s
