### ISSUE TITLE
why not a toString method?

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/upickle-pprint#176]
apart from `pprint.pprintln(t: T, width: Integer = null, ...)`,
why not a `pprint.toString(t: T, width: Integer = null, ...)`?

I understand that `pprintln` is streamed and it can print very large instances, but a `toString` method is also useful.

I can make a pull request with such a code (to be tested) if you like:

```
def toString[T: PPrint](t: T,
                          width: Integer = null,
                          height: Integer = null,
                          indent: Integer = null,
                          colors: Colors = null)
                         (implicit cfg: Config = Config.Defaults.PPrintConfig): String = {
    tokenize(t, width, height, indent, colors)(implicitly[PPrint[T]], cfg).mkString
}
```

**Comment by lihaoyi** [comment]
Sure I can see the use. Let's call it `stringify` rather than `toString`, since `toString` is already pretty standard and has a meaning/signature that isn't what this is
