### ISSUE TITLE
Serialize case classes as tuples (positional arguments)

### ISSUE THREAD

**Issue by strelec** [lihaoyi/upickle-pprint#193]
I suggest we introduce another annotation to the serialized case class:

`@Positional`

Whis way `case class A(a: Int, b: String, c: Boolean = false)` / `A(12, "Some string")` could simply get serialized to `[12,"Some string"]`. This would decrease the amount of information about the code that leaks to the user and would also greatly decrease the amount of data transferred.

**Comment by lihaoyi** [comment]
Already doable using http://www.lihaoyi.com/upickle-pprint/upickle/#CustomConfiguration

**Comment by strelec** [comment]
No, this is not what I mean.

I mean something automatic, without specifying the serialization rules for each case class separately.
