### ISSUE TITLE
Control serialization of a certain property across many classes in a DRY manner

### ISSUE THREAD

**Issue by ramnivas** [lihaoyi/upickle-pprint#40]
I am wondering what would be a good (=DRY) way to modify serialization and deserialization of a certain property in many classes.

I have a bunch of model classes of the following structure (somewhat simplified). I am persisting them using Slick, where such a structure is fairly common:

```scala
trait Entity {
  def id: Option[Long]
}

case class Person(fName: String, lName: String, id: Option[Long] = None) extends Entity

case class Organization(name: String, id: Option[Long] = None) extends Entity

// and so on...
```

Currently, uPickle serializes the `id` property as an array:
```
{
   ...
   id: [1234]
}
```

I am looking for a way to map the `id` property as follows:
* If `id` is `None`, omit the property. uPickle already does this, since the `id` property's default is `None`.
* If `id` is `Some(value)`, just serialize the `value`:
```
{
   ...
   id: 1234
}
```

What would be a good way, short of writing either a custom `apply()` and `unapply()` and the attendant parallel set of classes or writing a `Reader` and `Writer` for each model class?

**Comment by netvl** [comment]
I have some work on this in my branch [here](https://github.com/netvl/upickle/commits/case-class-filters). It depends on #65, so I'm not submitting it yet.

It is based on a suggestion by @lihaoyi in #43: a new implicit configuration called `Filter` is added. It is applied to each field upon serialization and deserialization and it controls the way this field is serialized. For example, it can omit the field from the output entirely. There are already some `Filter` implementations. One of them, for example, allows serializing `Option` fields as absent keys.

It required some rewrite of macros, and now most of `GeneratedUtil` and all of `CaseNR` and `CaseNW` are obsolete.

**Comment by lihaoyi** [comment]
"Serialization of properties across all classes" can now be coarsely controlled at the `Js.Value` level using Custom Configurations, an example of which is provided in https://github.com/lihaoyi/upickle-pprint/commit/f159ec35a59a8cacfb97da0c2665fcea033467b7

Let me know if that doesn't work for you or if you want something more fine-grained
