### ISSUE TITLE
UPickle doesn't work with overloaded apply methods

### ISSUE THREAD

**Issue by ramnivas** [lihaoyi/upickle-pprint#48]
Consider:

```scala
package com.example

import upickle._

case class Container(value: String)

object Container {
  def apply(intValue: Int): Container = Container(intValue.toString)
}

object ContainerApp extends App {
  write(Container("V"))
}
```

Compiling this leads to an error:
```
[error] /Users/ramnivas/test-dev/upickle-issue/src/main/scala/com/example/OverloadedApply.scala:14: uPickle does not know how to write [com.example.Container]s; define an implicit Writer[com.example.Container] to teach it how
[error]   val cWritten = write(c)
```

If I remove the `apply(Int)` method, it compiles fine.

Even the following compiles fine (has an auxiliary constructor; requires `new` when using that constructor):

```scala
package com.example

import upickle._

case class Container(value: String) {
  def this(intValue: Int) = this(intValue.toString)
}

object ContainerApp extends App {
  write(new Container(5))
}
```

I think uPickle should consider only the primary `apply` method, much the same way it seems to consider only the primary constructor.

**Comment by Kyprus** [comment]
I just ran into this issue. My opinion is that upickle should only use the primary apply method and if you want to customize serialization you implement a reader/writer. I think it's confusing that other apply overloads would change how upickle works.

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/upickle-pprint/commit/b8d897e8f589e2144d668d4b3978b371232eb591 to only ever use the primary apply which matches the primary constructor. Customization via custom apply/unapply is now broken and the unit tests have been removed.
