### ISSUE TITLE
Format generated JSON?

### ISSUE THREAD

**Issue by freewind** [lihaoyi/upickle-pprint#81]
The generated JSON is just in one line, is it possible to format it?

I'm using upickle on both server and client side, and will write generated JSON to a file and also commit it to git repo, so a formatted one is better for read and merge.

For now, I have to import `argonaut` on the server side just for formatting.

**Comment by tindzk** [comment]
You could have a look at the [``Renderer`` trait](https://github.com/lihaoyi/upickle/blob/master/upickle/jvm/src/main/scala/upickle/json/Jawn.scala#L50) and start with that. Adding formatting to it should be relatively straightforward. If you want formatting on the client-side too, you'll have to move the code to ``shared/src/main/``.
